Eq(1) = (I4+mb*LBcm^2)*cos(qa)*Dqa*Dqb + sin(qb)*cos(qa)*((I6+mb*LBcm^2)*sin(qb)*...
    Dqa*Dqb-DHprop-I5*sin(qb)*Dqa*Dqb-(I6*cos(qb)+LBcm*mb*(La+LBcm*cos(qb)))*DDqa)...
- Fa*Hprop^2*(Lb+La*cos(qb))*(sin(qa)*cos(qc)+sin(qb)*sin(qc)*cos(qa)) - cos(qa)*cos(qb)...
*(Fa*Hprop^2*sin(qc)*(Lf-La*sin(qb))+Hprop*Dqb+(I6+mb*LBcm^2)*cos(qb)*Dqa*Dqb-I5...
*cos(qb)*Dqa*Dqb-I5*sin(qb)*DDqa) - sin(qa)*(La*LBcm*mb*sin(qb)*Dqb^2+I5*sin(qb)*cos(qb)*...
Dqa^2-g*LBcm*mb-g*La*mb*cos(qb)-Hprop*sin(qb)*Dqa-sin(qb)*(I6*cos(qb)+LBcm*mb*(...
La+LBcm*cos(qb)))*Dqa^2-(I4+mb*LBcm^2+La*LBcm*mb*cos(qb))*DDqb);

Eq(2) = (I4+mb*LBcm^2)*cos(qa)*Dqa*Dqb + sin(qb)*cos(qa)*((I6+mb*LBcm^2)*sin(qb)...
    *Dqa*Dqb-DHprop-I5*sin(qb)*Dqa*Dqb-(I6*cos(qb)+LBcm*mb*(La+LBcm*cos(qb)))*DDqa)...
- Fa*Lb*Hprop^2*(sin(qa)*cos(qc)+sin(qb)*sin(qc)*cos(qa)) - cos(qa)*cos(qb)*(Fa*Lf*Hprop^2*...
sin(qc)+Hprop*Dqb+(I6+mb*LBcm^2)*cos(qb)*Dqa*Dqb-I5*cos(qb)*Dqa*Dqb-I5*sin(qb)*DDqa)...
- sin(qa)*(I5*sin(qb)*cos(qb)*Dqa^2-g*LBcm*mb-Hprop*sin(qb)*Dqa-sin(qb)*(I6*...
cos(qb)+LBcm*mb*(La+LBcm*cos(qb)))*Dqa^2-(I4+mb*LBcm^2)*DDqb);